//
//  CreatePlacePresenter.swift
//  Places
//
//  Created by Andressa Valengo on 24/01/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePlacePresentationLogic
{
  func presentSomething(response: CreatePlace.CreatePlace.Response)
}

class CreatePlacePresenter: CreatePlacePresentationLogic
{
  weak var viewController: CreatePlaceDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreatePlace.CreatePlace.Response)
  {
    let viewModel = CreatePlace.CreatePlace.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
