//
//  CreatePlaceModels.swift
//  Places
//
//  Created by Andressa Valengo on 24/01/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreatePlace
{
  
  struct PlaceInputFields
  {
    
    // MARK: Place info
    var name: String
  }
  
  // MARK: Use cases
  
  enum CreatePlace
  {
    struct Request
    {
      var placeInputFields: PlaceInputFields
    }
    struct Response
    {
      var place: Place?
    }
    struct ViewModel
    {
      var place: Place?
    }
  }
}
