//
//  CreatePlaceInteractor.swift
//  Places
//
//  Created by Andressa Valengo on 24/01/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePlaceBusinessLogic
{
  func doSomething(request: CreatePlace.CreatePlace.Request)
}

protocol CreatePlaceDataStore
{
  //var name: String { get set }
}

class CreatePlaceInteractor: CreatePlaceBusinessLogic, CreatePlaceDataStore
{
  var presenter: CreatePlacePresentationLogic?
  var worker: CreatePlaceWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreatePlace.CreatePlace.Request)
  {
    worker = CreatePlaceWorker()
    worker?.doSomeWork()
    
    let response = CreatePlace.CreatePlace.Response()
    presenter?.presentSomething(response: response)
  }
}
